package mapsapi

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "$(go-sdk-folder)/services/preview/maps/1.0/maps"
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/date"
)

        // AliasClientAPI contains the set of methods on the AliasClient type.
        type AliasClientAPI interface {
            AssignPreview(ctx context.Context, aliasID string, resourceID string) (result maps.SetObject, err error)
            CreatePreview(ctx context.Context) (result maps.AliasCreateResponse, err error)
            DeletePreview(ctx context.Context, aliasID string) (result maps.SetObject, err error)
            ListPreview(ctx context.Context) (result maps.AliasListResponse, err error)
        }

        var _ AliasClientAPI = (*maps.AliasClient)(nil)
        // DataClientAPI contains the set of methods on the DataClient type.
        type DataClientAPI interface {
            DeletePreview(ctx context.Context, udid string) (result maps.SetObject, err error)
            DownloadPreview(ctx context.Context, udid string) (result maps.SetObject, err error)
            ListPreview(ctx context.Context) (result maps.DataListResponse, err error)
            UpdatePreview(ctx context.Context, udid string, updateContent interface{}) (result maps.DataUpdatePreviewFuture, err error)
            UploadPreview(ctx context.Context, dataFormat maps.UploadDataFormat, uploadContent interface{}) (result maps.DataUploadPreviewFuture, err error)
        }

        var _ DataClientAPI = (*maps.DataClient)(nil)
        // DatasetClientAPI contains the set of methods on the DatasetClient type.
        type DatasetClientAPI interface {
            CreatePreview(ctx context.Context, conversionID string, udid string, datasetID string, description string) (result maps.DatasetCreatePreviewFuture, err error)
            DeletePreview(ctx context.Context, datasetID string) (result maps.SetObject, err error)
            ImportPreview(ctx context.Context, datasetID string, udid string) (result maps.DatasetImportPreviewFuture, err error)
            ListPreview(ctx context.Context) (result maps.DatasetListResponse, err error)
        }

        var _ DatasetClientAPI = (*maps.DatasetClient)(nil)
        // ElevationClientAPI contains the set of methods on the ElevationClient type.
        type ElevationClientAPI interface {
            GetDataForBoundingBox(ctx context.Context, bounds []string, rows float64, columns float64) (result maps.BoundingBoxResult, err error)
            GetDataForPoints(ctx context.Context, points [][]string) (result maps.PointsResult, err error)
            GetDataForPolyline(ctx context.Context, lines [][]string, samples *float64) (result maps.LinesResult, err error)
            PostDataForPoints(ctx context.Context, pointsRequestBody []maps.CoordinateAbbreviated) (result maps.PointsResult, err error)
            PostDataForPolyline(ctx context.Context, linesRequestBody []maps.CoordinateAbbreviated, samples *float64) (result maps.LinesResult, err error)
        }

        var _ ElevationClientAPI = (*maps.ElevationClient)(nil)
        // ConversionClientAPI contains the set of methods on the ConversionClient type.
        type ConversionClientAPI interface {
            ConvertPreview(ctx context.Context, udid string, description string) (result maps.ConversionConvertPreviewFuture, err error)
            DeletePreview(ctx context.Context, conversionID string) (result maps.SetObject, err error)
            ListPreview(ctx context.Context) (result maps.ConversionListResponse, err error)
        }

        var _ ConversionClientAPI = (*maps.ConversionClient)(nil)
        // FeatureStateClientAPI contains the set of methods on the FeatureStateClient type.
        type FeatureStateClientAPI interface {
            CreateStatesetPreview(ctx context.Context, datasetID string, statesetCreateRequestBody maps.StylesObject) (result maps.StatesetCreatedResponse, err error)
            DeleteStatePreview(ctx context.Context, statesetID string, featureID string, stateKeyName string) (result autorest.Response, err error)
            DeleteStatesetPreview(ctx context.Context, statesetID string) (result autorest.Response, err error)
            GetStatesetPreview(ctx context.Context, statesetID string) (result maps.StatesetGetResponse, err error)
            GetStatesPreview(ctx context.Context, statesetID string, featureID string) (result maps.FeatureStatesStructure, err error)
            ListStatesetPreview(ctx context.Context) (result maps.StatesetListResponse, err error)
            PutStatesetPreview(ctx context.Context, statesetID string, statesetStyleUpdateRequestBody maps.StylesObject) (result autorest.Response, err error)
            UpdateStatesPreview(ctx context.Context, statesetID string, featureID string, featureStateUpdateRequestBody maps.FeatureStatesStructure) (result autorest.Response, err error)
        }

        var _ FeatureStateClientAPI = (*maps.FeatureStateClient)(nil)
        // GeolocationClientAPI contains the set of methods on the GeolocationClient type.
        type GeolocationClientAPI interface {
            GetIPToLocationPreview(ctx context.Context, IP string) (result maps.IPAddressToLocationResult, err error)
        }

        var _ GeolocationClientAPI = (*maps.GeolocationClient)(nil)
        // MobilityClientAPI contains the set of methods on the MobilityClient type.
        type MobilityClientAPI interface {
            GetMetroAreaInfoPreview(ctx context.Context, query int32, detailType []maps.MetroAreaDetailType, language string) (result maps.MetroAreaInfoResponse, err error)
            GetMetroAreaPreview(ctx context.Context, query string, queryType maps.MetroAreaQueryType, language string) (result maps.MetroAreaResponse, err error)
            GetNearbyTransitPreview(ctx context.Context, query string, metroID *int32, limit *int32, radius *int32, objectType string, language string) (result maps.NearbyTransitResponse, err error)
            GetRealTimeArrivalsPreview(ctx context.Context, query string, metroID *int32, queryType maps.RealTimeArrivalsQueryType, stopQueryType maps.StopQueryType, limit *int32, maxMinutesInFuture *int32, transitType []maps.TransitTypeFilter, agency []string, agencyType maps.AgencyType, timeoutInSeconds *int32, language string) (result maps.RealTimeArrivalsResponse, err error)
            GetTransitItineraryPreview(ctx context.Context, query string, detailType []maps.TransitItineraryDetailType, language string) (result maps.TransitItineraryResponse, err error)
            GetTransitLineInfoPreview(ctx context.Context, query string, metroID *int32, detailType []maps.TransitLineDetailType, language string) (result maps.TransitLineInfoResponse, err error)
            GetTransitRoutePreview(ctx context.Context, origin string, destination string, metroID *int32, originType maps.OriginType, destinationType maps.DestinationType, modeType []maps.ModeType, transitType []maps.TransitTypeFilter, agency []string, agencyType maps.AgencyType, timeParameter string, timeType maps.TimeType, routeType maps.TransitRouteType, bikeType string, language string) (result maps.TransitRouteResponse, err error)
            GetTransitStopInfoPreview(ctx context.Context, query string, metroID *int32, queryType maps.TransitStopQueryType, detailType []maps.TransitStopDetailType, language string) (result maps.TransitStopInfoResponse, err error)
        }

        var _ MobilityClientAPI = (*maps.MobilityClient)(nil)
        // RenderClientAPI contains the set of methods on the RenderClient type.
        type RenderClientAPI interface {
            GetCopyrightCaption(ctx context.Context, formatParameter maps.TextFormat) (result maps.CopyrightCaptionResult, err error)
            GetCopyrightForTile(ctx context.Context, formatParameter maps.TextFormat, zoom int32, xTileIndex int32, yTileIndex int32, textParameter string) (result maps.CopyrightTileResult, err error)
            GetCopyrightForWorld(ctx context.Context, formatParameter maps.TextFormat, textParameter string) (result maps.CopyrightWorldResult, err error)
            GetCopyrightFromBoundingBox(ctx context.Context, formatParameter maps.TextFormat, mincoordinates string, maxcoordinates string, textParameter string) (result maps.CopyrightBoundingResult, err error)
            GetMapImage(ctx context.Context, layer maps.StaticMapLayer, style maps.MapImageStyle, zoom *int32, center string, bbox string, height *int32, width *int32, language string, view string, pins []string, pathParameter []string) (result maps.ReadCloser, err error)
            GetMapImageryTile(ctx context.Context, zoom int32, xTileIndex int32, yTileIndex int32) (result maps.ReadCloser, err error)
            GetMapStateTilePreview(ctx context.Context, zoom int32, xTileIndex int32, yTileIndex int32, statesetID string) (result maps.ReadCloser, err error)
            GetMapTile(ctx context.Context, formatParameter maps.TileFormat, layer maps.MapTileLayer, style maps.MapTileStyle, zoom int32, xTileIndex int32, yTileIndex int32, tileSize maps.MapTileSize, language string, view string) (result maps.ReadCloser, err error)
        }

        var _ RenderClientAPI = (*maps.RenderClient)(nil)
        // RenderV2ClientAPI contains the set of methods on the RenderV2Client type.
        type RenderV2ClientAPI interface {
            GetMapTilePreview(ctx context.Context, tilesetID maps.TilesetID, zoom int32, xTileIndex int32, yTileIndex int32, timeStamp string, tileSize maps.TileSize, language string, view string) (result maps.String, err error)
        }

        var _ RenderV2ClientAPI = (*maps.RenderV2Client)(nil)
        // RouteClientAPI contains the set of methods on the RouteClient type.
        type RouteClientAPI interface {
            GetRouteDirections(ctx context.Context, formatParameter maps.TextFormat, query string, maxAlternatives *int32, alternativeType maps.AlternativeRouteType, minDeviationDistance *int32, arriveAt *date.Time, departAt *date.Time, minDeviationTime *int32, instructionsType maps.RouteInstructionsType, language string, computeBestOrder *bool, routeRepresentation maps.RouteRepresentation, computeTravelTimeFor maps.ComputeTravelTimeFor, vehicleHeading *int32, report string, sectionType maps.SectionType, vehicleAxleWeight *int32, vehicleWidth *float64, vehicleHeight *float64, vehicleLength *float64, vehicleMaxSpeed *int32, vehicleWeight *int32, vehicleCommercial *bool, windingness maps.Windingness, hilliness maps.Hilliness, travelMode maps.TravelMode, avoid maps.Avoid, traffic *bool, routeType maps.RouteType, vehicleLoadType maps.VehicleLoadType, vehicleEngineType maps.VehicleEngineType, constantSpeedConsumptionInLitersPerHundredkm *float64, currentFuelInLiters *float64, auxiliaryPowerInLitersPerHour *float64, fuelEnergyDensityInMJoulesPerLiter *float64, accelerationEfficiency *float64, decelerationEfficiency *float64, uphillEfficiency *float64, downhillEfficiency *float64, constantSpeedConsumptionInkWhPerHundredkm string, currentChargeInkWh string, maxChargeInkWh string, auxiliaryPowerInkW string) (result maps.RouteDirectionsResponse, err error)
            GetRouteRange(ctx context.Context, formatParameter maps.TextFormat, query string, fuelBudgetInLiters *float64, energyBudgetInkWh *float64, timeBudgetInSec *float64, distanceBudgetInMeters *float64, departAt *date.Time, routeType maps.RouteType, traffic *bool, avoid maps.Avoid, travelMode maps.TravelMode, hilliness maps.Hilliness, windingness maps.Windingness, vehicleAxleWeight *int32, vehicleWidth *float64, vehicleHeight *float64, vehicleLength *float64, vehicleMaxSpeed *int32, vehicleWeight *int32, vehicleCommercial *bool, vehicleLoadType maps.VehicleLoadType, vehicleEngineType maps.VehicleEngineType, constantSpeedConsumptionInLitersPerHundredkm *float64, currentFuelInLiters *float64, auxiliaryPowerInLitersPerHour *float64, fuelEnergyDensityInMJoulesPerLiter *float64, accelerationEfficiency *float64, decelerationEfficiency *float64, uphillEfficiency *float64, downhillEfficiency *float64, constantSpeedConsumptionInkWhPerHundredkm string, currentChargeInkWh string, maxChargeInkWh string, auxiliaryPowerInkW string) (result maps.RouteRangeResponse, err error)
            PostRouteDirections(ctx context.Context, formatParameter maps.TextFormat, query string, routeDirectionsRequestBody maps.RouteDirectionsRequestBody, maxAlternatives *int32, alternativeType maps.AlternativeRouteType, minDeviationDistance *int32, minDeviationTime *int32, instructionsType maps.RouteInstructionsType, language string, computeBestOrder *bool, routeRepresentation maps.RouteRepresentation, computeTravelTimeFor maps.ComputeTravelTimeFor, vehicleHeading *int32, report string, sectionType maps.SectionType, arriveAt *date.Time, departAt *date.Time, vehicleAxleWeight *int32, vehicleLength *float64, vehicleHeight *float64, vehicleWidth *float64, vehicleMaxSpeed *int32, vehicleWeight *int32, vehicleCommercial *bool, windingness maps.Windingness, hilliness maps.Hilliness, travelMode maps.TravelMode, avoid maps.Avoid, traffic *bool, routeType maps.RouteType, vehicleLoadType maps.VehicleLoadType, vehicleEngineType maps.VehicleEngineType, constantSpeedConsumptionInLitersPerHundredkm *float64, currentFuelInLiters *float64, auxiliaryPowerInLitersPerHour *float64, fuelEnergyDensityInMJoulesPerLiter *float64, accelerationEfficiency *float64, decelerationEfficiency *float64, uphillEfficiency *float64, downhillEfficiency *float64, constantSpeedConsumptionInkWhPerHundredkm string, currentChargeInkWh string, maxChargeInkWh string, auxiliaryPowerInkW string) (result maps.RouteDirectionsResponse, err error)
            PostRouteDirectionsBatch(ctx context.Context, routeDirectionsBatchRequestBody maps.BatchRequestBody) (result maps.RoutePostRouteDirectionsBatchFuture, err error)
            PostRouteMatrix(ctx context.Context, routeMatrixBody maps.RouteMatrixRequestBody, waitForResults *bool, computeTravelTimeFor maps.ComputeTravelTimeFor, sectionType maps.SectionType, arriveAt *date.Time, departAt *date.Time, vehicleAxleWeight *int32, vehicleLength *float64, vehicleHeight *float64, vehicleWidth *float64, vehicleMaxSpeed *int32, vehicleWeight *int32, windingness maps.Windingness, hilliness maps.Hilliness, travelMode maps.TravelMode, avoid maps.Avoid, traffic *bool, routeType maps.RouteType, vehicleLoadType maps.VehicleLoadType) (result maps.RoutePostRouteMatrixFuture, err error)
        }

        var _ RouteClientAPI = (*maps.RouteClient)(nil)
        // SearchClientAPI contains the set of methods on the SearchClient type.
        type SearchClientAPI interface {
            GetSearchAddress(ctx context.Context, formatParameter maps.TextFormat, query string, typeahead *bool, limit *int32, ofs *int32, countrySet []string, lat *float64, lon *float64, radius *float64, topLeft string, btmRight string, language string, extendedPostalCodesFor string, view string) (result maps.SearchAddressResponse, err error)
            GetSearchAddressReverse(ctx context.Context, formatParameter maps.TextFormat, query string, language string, returnSpeedLimit *bool, heading *float64, radius *float64, number string, returnRoadUse *bool, roadUse string, allowFreeformNewline *bool, returnMatchType *bool, entityType maps.EntityType, view string) (result maps.SearchAddressReverseResponse, err error)
            GetSearchAddressReverseCrossStreet(ctx context.Context, formatParameter maps.TextFormat, query string, limit *int32, heading *float64, radius *float64, language string, view string) (result maps.SearchAddressReverseCrossStreetResponse, err error)
            GetSearchAddressStructured(ctx context.Context, formatParameter maps.TextFormat, countryCode string, language string, limit *int32, ofs *int32, streetNumber string, streetName string, crossStreet string, municipality string, municipalitySubdivision string, countryTertiarySubdivision string, countrySecondarySubdivision string, countrySubdivision string, postalCode string, extendedPostalCodesFor string, view string) (result maps.SearchAddressStructuredResponse, err error)
            GetSearchFuzzy(ctx context.Context, formatParameter maps.TextFormat, query string, typeahead *bool, limit *int32, ofs *int32, categorySet []int32, countrySet []string, lat *float64, lon *float64, radius *float64, topLeft string, btmRight string, language string, extendedPostalCodesFor string, minFuzzyLevel *int32, maxFuzzyLevel *int32, idxSet []maps.SearchIndexSet, brandSet []string, connectorSet []maps.ConnectorSet, view string, openingHours maps.OpeningHours) (result maps.SearchFuzzyResponse, err error)
            GetSearchNearby(ctx context.Context, formatParameter maps.TextFormat, lat float64, lon float64, limit *int32, ofs *int32, categorySet []int32, countrySet []string, radius *float64, language string, extendedPostalCodesFor string, brandSet []string, connectorSet []maps.ConnectorSet, view string) (result maps.SearchNearbyResponse, err error)
            GetSearchPOI(ctx context.Context, formatParameter maps.TextFormat, query string, typeahead *bool, limit *int32, ofs *int32, categorySet []int32, countrySet []string, lat *float64, lon *float64, radius *float64, topLeft string, btmRight string, language string, extendedPostalCodesFor string, brandSet []string, connectorSet []maps.ConnectorSet, view string, openingHours maps.OpeningHours) (result maps.SearchPoiResponse, err error)
            GetSearchPOICategory(ctx context.Context, formatParameter maps.TextFormat, query string, typeahead *bool, limit *int32, ofs *int32, categorySet []int32, countrySet []string, lat *float64, lon *float64, radius *float64, topLeft string, btmRight string, language string, extendedPostalCodesFor string, brandSet []string, connectorSet []maps.ConnectorSet, view string, openingHours maps.OpeningHours) (result maps.SearchPoiCategoryResponse, err error)
            GetSearchPOICategoryTreePreview(ctx context.Context, language string) (result maps.PoiCategoryResponse, err error)
            GetSearchPolygon(ctx context.Context, geometries string) (result maps.SearchPolygonResponse, err error)
            PostSearchAddressBatch(ctx context.Context, searchAddressBatchRequestBody maps.BatchRequestBody) (result maps.SearchPostSearchAddressBatchFuture, err error)
            PostSearchAddressReverseBatch(ctx context.Context, searchAddressReverseBatchRequestBody maps.BatchRequestBody) (result maps.SearchPostSearchAddressReverseBatchFuture, err error)
            PostSearchAlongRoute(ctx context.Context, query string, formatParameter maps.TextFormat, maxDetourTime int32, searchAlongRouteRequestBody maps.SearchAlongRouteRequestBody, categorySet []int32, limit *int32, brandSet []string, connectorSet []maps.ConnectorSet, view string, openingHours maps.OpeningHours) (result maps.SearchAlongRouteResponse, err error)
            PostSearchFuzzyBatch(ctx context.Context, searchFuzzyBatchRequestBody maps.BatchRequestBody) (result maps.SearchPostSearchFuzzyBatchFuture, err error)
            PostSearchInsideGeometry(ctx context.Context, query string, formatParameter maps.TextFormat, searchInsideGeometryRequestBody maps.SearchInsideGeometryRequestBody, limit *int32, language string, categorySet []int32, extendedPostalCodesFor string, idxSet []maps.SearchIndexSet, view string, openingHours maps.OpeningHours) (result maps.SearchGeometryResponse, err error)
        }

        var _ SearchClientAPI = (*maps.SearchClient)(nil)
        // SpatialClientAPI contains the set of methods on the SpatialClient type.
        type SpatialClientAPI interface {
            GetBuffer(ctx context.Context, udid string, distances string) (result maps.BufferResponse, err error)
            GetClosestPoint(ctx context.Context, udid string, lat float64, lon float64, numberOfClosestPoints *int32) (result maps.GetClosestPointResponse, err error)
            GetGeofence(ctx context.Context, deviceID string, udID string, lat float64, lon float64, z *float64, userTime string, searchBuffer *float64, isAsync *bool, mode maps.GeofenceMode) (result maps.GeofenceResponse, err error)
            GetGreatCircleDistance(ctx context.Context, query string) (result maps.GreatCircleDistanceResponse, err error)
            GetPointInPolygon(ctx context.Context, udid string, lat float64, lon float64) (result maps.GetPointInPolygonResponse, err error)
            PostBuffer(ctx context.Context, bufferRequestBody maps.BufferRequestBody) (result maps.BufferResponse, err error)
            PostClosestPoint(ctx context.Context, lat float64, lon float64, closestPointRequestBody maps.GeoJSONFeatureCollection, numberOfClosestPoints *int32) (result maps.PostClosestPointResponse, err error)
            PostGeofence(ctx context.Context, deviceID string, lat float64, lon float64, searchGeofenceRequestBody maps.GeoJSONFeatureCollection, z *float64, userTime string, searchBuffer *float64, isAsync *bool, mode maps.GeofenceMode) (result maps.GeofenceResponse, err error)
            PostPointInPolygon(ctx context.Context, lat float64, lon float64, pointInPolygonRequestBody maps.GeoJSONFeatureCollection) (result maps.PostPointInPolygonResponse, err error)
        }

        var _ SpatialClientAPI = (*maps.SpatialClient)(nil)
        // TilesetClientAPI contains the set of methods on the TilesetClient type.
        type TilesetClientAPI interface {
            CreatePreview(ctx context.Context, datasetID string, description string) (result maps.TilesetCreatePreviewFuture, err error)
            DeletePreview(ctx context.Context, tilesetID string) (result maps.SetObject, err error)
            ListPreview(ctx context.Context) (result maps.TilesetListResponse, err error)
        }

        var _ TilesetClientAPI = (*maps.TilesetClient)(nil)
        // TimezoneClientAPI contains the set of methods on the TimezoneClient type.
        type TimezoneClientAPI interface {
            GetTimezoneByCoordinates(ctx context.Context, query string, acceptLanguage string, options maps.TimezoneOptions, timeStamp *date.Time, transitionsFrom *date.Time, transitionsYears *int32) (result maps.TimezoneByCoordinatesResult, err error)
            GetTimezoneByID(ctx context.Context, query string, acceptLanguage string, options maps.TimezoneOptions, timeStamp *date.Time, transitionsFrom *date.Time, transitionsYears *int32) (result maps.TimezoneByIDResult, err error)
            GetTimezoneEnumIANA(ctx context.Context) (result maps.ListIanaID, err error)
            GetTimezoneEnumWindows(ctx context.Context) (result maps.ListTimezoneEnumWindow, err error)
            GetTimezoneIANAVersion(ctx context.Context) (result maps.TimezoneIanaVersionResult, err error)
            GetTimezoneWindowsToIANA(ctx context.Context, query string, territory string) (result maps.ListIanaID, err error)
        }

        var _ TimezoneClientAPI = (*maps.TimezoneClient)(nil)
        // TrafficClientAPI contains the set of methods on the TrafficClient type.
        type TrafficClientAPI interface {
            GetTrafficFlowSegment(ctx context.Context, formatParameter maps.TextFormat, style maps.TrafficFlowSegmentStyle, zoom int32, query string, unit maps.SpeedUnit, thickness *int32, openLr *bool) (result maps.TrafficFlowSegmentResult, err error)
            GetTrafficFlowTile(ctx context.Context, formatParameter maps.TileFormat, style maps.TrafficFlowTileStyle, zoom int32, xTileIndex int32, yTileIndex int32, thickness *int32) (result maps.String, err error)
            GetTrafficIncidentDetail(ctx context.Context, formatParameter maps.TextFormat, style maps.TrafficIncidentDetailStyle, boundingbox string, boundingZoom int32, trafficmodelid string, language string, projection string, geometries maps.IncidentGeometryType, expandCluster *bool, originalPosition *bool) (result maps.TrafficIncidentDetailResult, err error)
            GetTrafficIncidentTile(ctx context.Context, formatParameter maps.TileFormat, style maps.TrafficIncidentTileStyle, zoom int32, xTileIndex int32, yTileIndex int32, trafficState string) (result maps.TrafficIncidentTileResult, err error)
            GetTrafficIncidentViewport(ctx context.Context, formatParameter maps.TextFormat, boundingbox string, boundingzoom int32, overviewbox string, overviewzoom int32, copyright bool) (result maps.TrafficIncidentViewportResult, err error)
        }

        var _ TrafficClientAPI = (*maps.TrafficClient)(nil)
        // WeatherClientAPI contains the set of methods on the WeatherClient type.
        type WeatherClientAPI interface {
            GetCurrentConditions(ctx context.Context, query string, unit maps.Unit, details string, duration *int32, language string) (result maps.CurrentConditionsResponse, err error)
            GetDailyForecast(ctx context.Context, query string, unit maps.Unit, duration *int32, language string) (result maps.DailyForecastResponse, err error)
            GetDailyIndices(ctx context.Context, query string, language string, duration *int32, indexID *int32, indexGroupID *int32) (result maps.DailyIndicesResponse, err error)
            GetHourlyForecast(ctx context.Context, query string, unit maps.Unit, duration *int32, language string) (result maps.HourlyForecastResponse, err error)
            GetMinuteForecast(ctx context.Context, query string, interval *int32, language string) (result maps.MinuteForecastResponse, err error)
            GetQuarterDayForecast(ctx context.Context, query string, unit maps.Unit, duration *int32, language string) (result maps.QuarterDayForecastResponse, err error)
            GetSevereWeatherAlerts(ctx context.Context, query string, language string, details string) (result maps.SevereWeatherAlertsResponse, err error)
            GetWeatherAlongRoute(ctx context.Context, query string, language string) (result maps.WeatherAlongRouteResponse, err error)
        }

        var _ WeatherClientAPI = (*maps.WeatherClient)(nil)
        // WFSClientAPI contains the set of methods on the WFSClient type.
        type WFSClientAPI interface {
            CollectionDefinitionPreview(ctx context.Context, datasetid string, collectionID string) (result maps.CollectionDefinition, err error)
            CollectionDescriptionPreview(ctx context.Context, datasetid string, collectionID string) (result maps.CollectionInfo, err error)
            CollectionsDescriptionPreview(ctx context.Context, datasetid string) (result maps.Content, err error)
            DeleteFeaturePreview(ctx context.Context, datasetid string, collectionID string, featureID string) (result autorest.Response, err error)
            GetFeaturePreview(ctx context.Context, datasetid string, collectionID string, featureID string) (result maps.Feature, err error)
            GetFeaturesPreview(ctx context.Context, datasetid string, collectionID string, limit *float64, bbox string, filter string) (result maps.FeatureCollectionGeoJSON, err error)
            GetLandingPagePreview(ctx context.Context, datasetid string) (result maps.Root, err error)
            GetRequirementsClassesPreview(ctx context.Context, datasetid string) (result maps.ReqClasses, err error)
        }

        var _ WFSClientAPI = (*maps.WFSClient)(nil)
